### ISSUE TITLE
Returning average miles

### ISSUE THREAD

**Issue by blakev** [BCoons05/ksl-alert-api#1]
https://github.com/BCoons05/ksl-alert-api/blob/a8b417e6a8eda74b28222ba4d168052921b1736a/app.py#L283

The SQLAlchemy function is performing an `average` inside the database, which is returning (most likely) a `Decimal` instance.

_Python docs on [`decimal.Decimal`](https://docs.python.org/3/library/decimal.html)._

The reason it would be a `Decimal` and not a `float` is you're averaging a column of integers, and floats have precision problems when dealing with exact information, like dollars and cents. Integers have guaranteed precision. Instead of converting the value to a `string` and splitting on the period, you could instead turn it into an `int` or `float` and return it as a JSON object.

Since your API is JSON-response based the return should probably be,

```python
return jsonify({
    'miles': int(average_miles[0][0]),
})
```

There are lots of ways to manipulate a `Decimal` instance,

```python
>>> from decimal import Decimal
>>>
>>> money = Decimal('3.99999')
>>> money
Decimal('3.99999')
>>> int(money)
3
>>> money.to_integral_value()
Decimal('4')
>>> int(money.to_integral_value())
4
>>> float(money)
3.99999
>>> round(float(money), 2)
4.0
>>> money.quantize(Decimal('1.00'))
Decimal('4.00')
>>> money.as_tuple()
DecimalTuple(sign=0, digits=(3, 9, 9, 9, 9, 9), exponent=-5)
>>>
```

**Comment by BCoons05** [comment]
What a guy! Thanks my man. Seems so obvious now.
